name: weekly_calendar
description: Effortlessly integrate this straightforward weekly calendar widget into your Flutter app for a seamless user experience. 
version: 0.1.2
homepage: https://github.com/mlballack/WeeklyCalendarForFlutter

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_gen_runner: ^5.5.0+1
  auto_route_generator: ^7.3.2


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/src/config/gen/
  inputs:
    - assets/icons/
  integrations:
    flutter_svg: true
    rive: true

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0